---
title: "Project code"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(fixest)
library(patchwork)
library(stargazer)
library(nlme)
library(plm)
library(readr)
library(tidyr)
library(pscl)
library(sandwich)
library(lmtest)
library(margins)
library(car)
library(effects)
library(nortest)
```



```{r reading, include=TRUE}

pitching <- read.csv("pitching_2015_2024.csv")


#selecting only pitchers with more than 50 IP because they will most likely have the most consistent data due to larger sample sizes.
pitching_selected <- pitching[ pitching$IP > 50, c("WHIP", "ERA", "HR.9", "Age", "K.9", "Team", "Season", "BB.9", "AVG")]



```



```{r}
knitr::opts_chunk$set(echo = FALSE)
# First Model
model1 <- lm(ERA ~ WHIP, data = pitching_selected)
summary(model1)
#Start iteratively adding variables
model2 <- lm(ERA ~ WHIP + HR.9, data = pitching_selected)
summary(model2)
```


```{r}
#Use anova to test significance of adding
anova(model1, model2)
```
```{r}
model3 <- lm(ERA ~ WHIP + HR.9 + K.9, data = pitching_selected)
summary(model3)
anova(model2, model3)

model4 <- lm(ERA ~ WHIP + HR.9 + K.9 + Age, data = pitching_selected)
summary(model4)
anova(model3, model4)
vif(model4)
```
```{r}
model5 <- lm(ERA ~ WHIP + HR.9 + K.9 + Age + Team, data = pitching_selected)
summary(model5)
anova(model4, model5)
vif(model4)
```
```{r}
pitching_selected$COL <- ifelse(pitching_selected$Team == "COL", 1, 0)
pitching_selected$CHC <- ifelse(pitching_selected$Team == "CHC", 1, 0)
pitching_selected$MIL <- ifelse(pitching_selected$Team == "MIL", 1, 0)
pitching_selected$OAK <- ifelse(pitching_selected$Team == "OAK", 1, 0)


modelTeam <- lm(ERA ~ WHIP + HR.9 + K.9 + Age + COL + CHC + MIL + OAK,
             data = pitching_selected)
summary(modelTeam)
anova(model4, modelTeam)

```

```{r}
model6 <- feols(ERA ~ WHIP + HR.9 + K.9 + Age + COL + CHC + MIL + OAK | Season, data = pitching_selected)
summary(model6)
```



```{r}
model7 <- lm(ERA ~ WHIP + HR.9 + K.9 + Age + BB.9 + AVG, data = pitching_selected)
summary(model6)
anova(model4, model7)
vif(model7)
```

```{r}
residuals <- residuals(model6)
hist(residuals)
#Anderson-Darling Test
ad_test <- ad.test(residuals)
ad_test
```

```{r}
plot(pitching_selected$WHIP, pitching_selected$ERA,main = "Relationship Between WHIP and ERA",xlab = "WHIP", ylab = "ERA")
plot(pitching_selected$HR.9, pitching_selected$ERA,main = "Relationship Between HRs per 9 and ERA",xlab = "HR per 9", ylab = "ERA")
plot(pitching_selected$Age, pitching_selected$ERA,main = "Relationship Between Age and ERA",xlab = "Age", ylab = "ERA")
plot(pitching_selected$K.9, pitching_selected$ERA,main = "Relationship Between Strikeouts per 9 and ERA",xlab = "Strikeouts per 9", ylab = "ERA")
```
```{r}
.007/mean(pitching_selected$ERA)
```

```{r}
# final model removed age because of practical significance
modelFinal <- feols(ERA ~ WHIP + HR.9 + K.9 + COL + CHC + MIL + OAK | Season, data = pitching_selected)
summary(modelFinal)


modelTest <- feols(ERA ~ 1 | Season, data = pitching_selected)
pitching_selected <- pitching_selected %>% mutate(ERA_resid2 = resid(modelTest))

# How much of 'educ' is absorbed by FE? (R^2 ~ 1 => little identifying variation left)
pitching_selected$ERA_resid2 <- resid(modelTest)

era_var2     <- var(pitching_selected$ERA, na.rm = TRUE)
era_residvar2 <- var(pitching_selected$ERA_resid2, na.rm = TRUE)

# “FE R Squared” for the regressor: how much of educ is explained by FE?
r2_fe_era <- 1 - era_residvar2 / era_var2
r2_fe_era
```

```{r}
summary_table <- pitching_selected %>%
  select(-Team, -Season) %>%       # drop non-numeric grouping variables
  summarise(across(
    .cols = everything(),
    .fns = list(
      mean = mean,
      min = min,
      max = max,
      median = median,
      sd = sd
    ),
    na.rm = TRUE
  ))

summary_table
```

